import fs from "fs";
let js = fs.readFileSync("src/commands/utility.js", "utf8");

const t = `  { id: 'security', shortLabel: 'Security', label: 'Security & Firewall', emoji: '<:security_and_firewall:1523672289500069940>', commands: ['\`!security\` **enable all** / **disable all** ?" Toggle all shields \`[extra owners]\`', '\`!scanserver\` ?" Scan and manage unauthorized bots \`[extra owners]\`', '\`!lockapps\` / \`!unlockapps\` ?" Manage slash commands server-wide \`[extra owners]\`', '\`!antinuke\` **config** ?" Open the interactive configuration panel \`[extra owners]\`', '\`!config\` **antinuke** / **antispam** / **antiinvite** / **antibot** / **maxwarnings** \`on|off\` \`[extra owners]\`', '\`!raidmode\` **on** / **off** ?" Auto-quarantine every new join during a raid \`[extra owners]\`', '\`!emergency\` **mode** / **end** ?" Strip dangerous permissions and hide channels \`[extra owners]\`', 'You MUST whitelist friendly bots (\`!botwhitelist add <ID>\`). Unwhitelisted bots will be instantly banned.'] },`;
const r = `  { id: 'security', shortLabel: 'Security', label: 'Security & Firewall', emoji: '<:security_and_firewall:1523672289500069940>', commands: ['\`!security\` **enable all** / **disable all** ?" Toggle all shields \`[extra owners]\`', '\`!scanserver\` ?" Scan and manage unauthorized bots \`[extra owners]\`', '\`!lockapps\` / \`!unlockapps\` ?" Manage slash commands server-wide \`[extra owners]\`', '\`!antinuke\` **config** ?" Open the interactive configuration panel \`[extra owners]\`', '\`!config\` **antinuke** / **antispam** / **antiinvite** / **antibot** / **maxwarnings** \`on|off\` \`[extra owners]\`', '\`!raidmode\` **on** / **off** ?" Auto-quarantine every new join during a raid \`[extra owners]\`', '\`!emergency\` **mode** / **end** ?" Strip dangerous permissions and hide channels \`[extra owners]\`', 'You MUST whitelist friendly bots (\`!botwhitelist add <ID>\`). Unwhitelisted bots will be instantly banned.'] },
  { id: 'np', shortLabel: 'No-Prefix', label: 'No-Prefix (NP) Bypass', emoji: '<:emoji_16:1521464002046328944>', commands: ['\`!np add user\` \`@user|id\` \`[duration]\` - Grant No-Prefix bypass \`[bot owner/np manager]\`', '\`!np add server\` \`id\` \`[duration]\` - Grant No-Prefix to entire server \`[bot owner/np manager]\`', '\`!np reset user\` \`id\` - Revoke user No-Prefix bypass \`[bot owner/np manager]\`', '\`!np reset server\` \`id\` - Revoke server No-Prefix bypass \`[bot owner/np manager]\`', '\`!np guide\` - View full No-Prefix system guide \`[np manager]\`'] },`;

js = js.replace(t, r);
fs.writeFileSync("src/commands/utility.js", js);
