import fs from "fs";

let js = fs.readFileSync("src/commands/utility.js", "utf8");

const startIdx = js.indexOf("const helpModules = [");
const newsfeedIdx = js.indexOf("newsfeed", startIdx);
const endIdx = js.indexOf("];", newsfeedIdx) + 2;

const newHelpModules = `const helpModules = [
    { id: 'antinuke', category: 'SECURITY & ACCESS CONTROL', shortLabel: 'Anti-Nuke', label: 'Anti-Nuke Engine', emoji: 'antinuke', commands: [
      "\`!antinuke\` - Toggle Anti-Nuke Engine (On/Off) \`[server owner]\`",
      "-# The Anti-Nuke engine instantly bans malicious admins and automatically restores deleted channels, roles, and emojis.",
      "\`!whitelist\` - Open Whitelist Manager \`[server owner]\`",
      "**Anti-Nuke Protection Coverage:**",
      "- Mass Channel Deletion / Creation",
      "- Mass Role Deletion / Creation",
      "- Mass Member Ban / Kick",
      "- Unauthorized Bot Additions",
      "- Webhook Creation Spam"
    ] },
    { id: 'filters', category: 'SECURITY & ACCESS CONTROL', shortLabel: 'Filters', label: 'Automod Filters', emoji: 'filters', commands: [
      "\`!automod config\` - Open Interactive Automod configuration \`[extra owners]\`",
      "**Automod Config Features:**",
      "- Anti-Spam & Rate Limiting (Mute/Kick/Ban)",
      "- Mass Mention & Raid Protection",
      "- Zalgo & Caps Lock Filters",
      "",
      "\`!automod advanced\` - Global link & invite toggles \`[extra owners]\`",
      "\`!automod bypass add @role\` - Bypass specific modules \`[extra owners]\`",
      "\`!automod bypass list\` - View bypassed roles \`[extra owners]\`",
      "\`!wordfilter\` - Manage the banned word list \`[extra owners]\`",
      "**Word Filter Options:**",
      "- Add/Remove banned phrases",
      "- View blocked words list",
      "",
      "\`!antilink\` - Open Interactive Anti-Link & Invite Dashboard \`[extra owners]\`",
      "\`!linksallow add|remove|list domain\` - Whitelist specific domains \`[extra owners]\`",
      "\`!blacklist add|remove|list phrase\` - Auto-delete phrases \`[extra owners]\`"
    ] },
    { id: 'quarantine', category: 'SECURITY & ACCESS CONTROL', shortLabel: 'Quarantine', label: 'Quarantine System', emoji: 'quarantine', commands: [
      "\`!qrmanager setup|setrole|setchannel|setvc|status\` - Manage system \`[extra owners]\`",
      "**Quarantine Manager Options:**",
      "- Set Isolation Role & Text Channel",
      "- Set Voice Channel Lock",
      "- View active system status",
      "",
      "\`!quarantine @user [reason]\` - Strip roles and isolate (alias: \`!qr\`) \`[extra owners]\`",
      "-# Instantly strips all roles from a user and locks them in a secure quarantine zone. Roles are safely cached for restoration.",
      "\`!unquarantine @user\` - Lift quarantine status \`[extra owners]\`",
      "\`!massquarantine @role\` - Quarantine all members of a role \`[extra owners]\`",
      "\`!massunquarantine\` - Release all currently quarantined members \`[extra owners]\`",
      "\`!lockdown on|off\` - Restrict channel to moderators only \`[extra owners]\`"
    ] },
    { id: 'whitelist', category: 'SECURITY & ACCESS CONTROL', shortLabel: 'Whitelist', label: 'Whitelist & Access', emoji: 'whitelist', commands: [
      "\`!whitelist\` - Open Global Whitelist Manager Dashboard \`[extra owners]\`",
      "**Whitelist Panel Options:**",
      "- View all authorized Extra Owners",
      "- View whitelisted Immune Bots",
      "",
      "\`!whitelist @user|@role\` - Direct access panel \`[extra owners]\`",
      "\`!auth\` - Configure Role Authorization Tiers \`[server owner]\`",
      "\`!tier\` - Check your authorization level \`[public]\`",
      "\`!botwhitelist add|remove <id>\` - Allow specific bots to join \`[server owner]\`",
      "-# Prevents unverified bots from being invited by rogue admins.",
      "\`!botwhitelist list\` - View immune bots \`[server owner]\`",
      "\`!userblacklist add|remove|list @user\` - Blacklist user from bot \`[extra owners]\`",
      "\`!extraowner add|remove|list @user\` - Grant full bot access \`[server owner]\`"
    ] },
    { id: 'verification', category: 'SECURITY & ACCESS CONTROL', shortLabel: 'Verify', label: 'Verification Gate', emoji: 'verification', commands: [
      "\`!verify setup\` - Initialize Captcha Verification system \`[extra owners]\`",
      "**Verification Features:**",
      "- Captcha Image Generation",
      "- Auto-assign Verified Role",
      "- Block automated bot accounts",
      "",
      "\`!verify config\` - Change verification difficulty and role \`[extra owners]\`"
    ] },
    { id: 'moderation', category: 'SERVER ADMINISTRATION', shortLabel: 'Moderation', label: 'Moderation Tools', emoji: 'moderation', commands: [
      "\`!ban / !kick / !mute / !warn\` - Standard moderation tools \`[extra owners]\`",
      "\`!timeout @user dur\` - Timeout a member \`[extra owners]\`",
      "\`!warnings / !clearwarns @user\` - View or wipe history \`[extra owners]\`",
      "\`/maxwarnings amount\` - Set maximum warning threshold \`[extra owners]\`",
      "",
      "\`!addrole / !removerole @user @roles\` - Safely assign multiple roles \`[extra owners]\`",
      "\`!striproles @user\` - Instantly strip all roles \`[extra owners]\`",
      "\`!massaddrole / !massremoverole @role\` - Mass role assignment \`[extra owners]\`",
      "\`!massstrip / !massrestore @role\` - Mass strip/restore a role \`[extra owners]\`",
      "",
      "\`!sync / !syncall\` - Sync channel permissions \`[extra owners]\`",
      "\`!purge 1-100\` - Bulk-delete messages \`[extra owners]\`",
      "\`!slowmode seconds\` - Set channel slowmode \`[extra owners]\`",
      "\`!createchannel / !deletechannel\` - Channel management \`[extra owners]\`",
      "\`!createrole / !deleterole\` - Role management \`[extra owners]\`",
      "\`!hide / !unhide\` - Hide text/voice channel \`[extra owners]\`",
      "\`!createthread / !archivethread / !deletethread\` - Thread management \`[extra owners]\`",
      "",
      "\`!ignore channel|category\` / \`!ignoreall\` - Block commands \`[admin]\`",
      "\`ur @user new_name\` - Rename user \`[extra owners]\`",
      "\`!snipe\` - Recover deleted message \`[extra owners]\`",
      "\`!ignorechan / !ignorecat\` - Blacklist commands in channel/category \`[admin]\`",
      "\`!wipeemojis\` - Delete all custom emojis from the server \`[extra owners]\`",
      "-# Opens a confirmation panel to securely wipe all emojis with a live progress tracker.",
      "\`!givemerole / !takemyrole\` - Self role assign \`[public]\`",
      "\`!cleanbadroles\` - Wipe unused roles \`[extra owners]\`",
      "\`!spampermit / !spamrevoke\` - Manage anti-spam bypass \`[extra owners]\`",
      "\`!adel / !radel\` - Auto-delete all messages from user \`[extra owners]\`",
      "\`!fck\` - Send direct Athena warning DM \`[server owner]\`",
      "\`!sethomevc @user / !unsethomevc\` - Lock a user to a specific VC \`[extra owners]\`",
      "\`!spamlist\` - List all permitted spam users \`[extra owners]\`",
      "\`!unban / !unbanall\` - Unban a specific user or mass-unban all users \`[extra owners]\`",
      "\`!unignoreall\` - Lift the mass command lock \`[admin]\`"
    ] },
    { id: 'tracking', category: 'SERVER ADMINISTRATION', shortLabel: 'Tracking', label: 'Engagement & Tracking', emoji: 'tracking', commands: [
      "\`!serverlogs autosetup\` - Setup Advanced Logging \`[extra owners]\`",
      "**Logging Capabilities:**",
      "- Message Deletions & Edits",
      "- Role Assignments & Changes",
      "- Channel Modifications",
      "- Voice Channel Joins/Leaves",
      "",
      "\`!invitesetup #channel\` - Advanced Invite Tracker \`[extra owners]\`",
      "\`!record start\` - Live VC audio recording \`[extra owners]\`",
      "\`!audit\` / \`!logs\` - Server logging toggles \`[extra owners]\`",
      "\`!youtube\` - Setup YouTube upload notifications \`[extra owners]\`",
      "\`!syncinvites\` - Retroactively sync invite data \`[extra owners]\`",
      "\`!setdeletelog\` - Set deleted message log channel \`[extra owners]\`",
      "\`!invitedisable\` - Disable invite tracking for the server \`[extra owners]\`"
    ] },
    { id: 'config', category: 'SERVER ADMINISTRATION', shortLabel: 'Config', label: 'Customization & Roles', emoji: 'config', commands: [
      "\`!prefix <new>\` - Change bot prefix \`[extra owners]\`",
      "\`!accent\` - Modify embed colors \`[extra owners]\`",
      "\`!autonick on\` - Standardize member nicknames \`[extra owners]\`",
      "\`!rrsetup\` - Setup Reaction Roles \`[extra owners]\`",
      "**Reaction Role Options:**",
      "- Multi-select Dropdowns",
      "- Emoji Buttons",
      "",
      "\`!setguildavatar\` - Set the bot's custom server-specific avatar \`[extra owners]\`",
      "\`!setguildbanner\` - Set the bot's custom server-specific banner \`[extra owners]\`",
      "\`!setstatschannel\` - Set a dedicated channel for stats commands \`[extra owners]\`"
    ] },
    { id: 'welcome', category: 'SERVER ADMINISTRATION', shortLabel: 'Welcome', label: 'Welcome System', emoji: 'welcome', commands: [
      "\`!welcome setup\` - Build interactive welcome messages \`[extra owners]\`",
      "**Welcome System Features:**",
      "- Custom Embed Builder",
      "- User Avatar & Username Tags",
      "- DM Welcome Messages",
      "",
      "\`!autorole add @role\` - Automatically assign roles on join \`[extra owners]\`",
      "\`!leave\` - Open the Leave Message Manager \`[extra owners]\`",
      "\`!autorole-config\` - Add or remove an autorole for new members \`[extra owners]\`"
    ] },
    { id: 'giveaways', category: 'COMMUNITY & ENGAGEMENT', shortLabel: 'Giveaways', label: 'Birthdays & Giveaways', emoji: 'giveaways', commands: [
      "\`!giveaway start\` / \`end\` / \`reroll\` - Giveaway management \`[extra owners]\`",
      "**Giveaway Features:**",
      "- Interactive Setup Panel",
      "- Duration & Winner Count",
      "- Automated Winner Drawing",
      "",
      "\`!birthday setchannel #channel\` - Set birthday announcements \`[extra owners]\`",
      "\`!birthday set / remove @user\` - Manage birthdays \`[extra owners]\`",
      "\`!birthday list\` - List birthdays \`[extra owners]\`",
      "\`!testbirthday\` - Send a test birthday announcement \`[extra owners]\`"
    ] },
    { id: 'triggers', category: 'COMMUNITY & ENGAGEMENT', shortLabel: 'Triggers', label: 'Auto-Responder', emoji: 'triggers', commands: [
      "\`!trigger create <match> | <resp>\` - Create auto-response \`[extra owners]\`",
      "-# The bot will automatically reply with the response when it sees the match trigger word.",
      "\`!trigger list\` - View triggers \`[public]\`",
      "\`!trigger delete\` - Remove trigger \`[extra owners]\`"
    ] },
    { id: 'autoreact', category: 'COMMUNITY & ENGAGEMENT', shortLabel: 'Auto-React', label: 'Auto-Reactions', emoji: 'autoreact', commands: [
      "\`!autoreact add <word> <emoji>\` - Automatically react to keywords \`[extra owners]\`",
      "-# The bot will automatically add the specified emoji reaction to messages containing the keyword.",
      "\`!autoreact list\` - View active reactions \`[public]\`",
      "\`!autoreact delete\` - Remove reaction \`[extra owners]\`"
    ] },
    { id: 'actions', category: 'COMMUNITY & ENGAGEMENT', shortLabel: 'Roleplay', label: 'Roleplay Actions', emoji: 'actions', commands: [
      "\`!hug / !kiss / !slap / !pat / !bite / !cuddle / !wink / !bonk / !bully / !cry / !handhold / !highfive / !nom / !poke / !yeet\` - Interact with users \`[public]\`",
      "-# Triggers an anime GIF embed with your roleplay action.",
      "\`!date @user\` - Go on a date \`[public]\`"
    ] },
    { id: 'leveling', category: 'COMMUNITY & ENGAGEMENT', shortLabel: 'Leveling', label: 'Leveling Engine', emoji: 'leveling', commands: [
      "\`!xpsetup\` - Launch interactive XP panel \`[extra owners]\`",
      "**XP System Panel Features:**",
      "- Multiplier Settings",
      "- Level Up Notification Channel",
      "- Role Rewards for Levels",
      "",
      "\`!rank [@user]\` - View level graphic \`[public]\`",
      "\`!leaderboard\` - View top active members \`[public]\`",
      "\`!givexp / !removexp\` - Modify user XP \`[extra owners]\`"
    ] },
    
    { id: 'voice', category: 'VOICE & MEDIA', shortLabel: 'Voice', label: 'Voice Management', emoji: 'voice', commands: [
      "\`!vcsetup\` - Setup Join-to-Create (JTC) channels \`[extra owners]\`",
      "\`!vclist\` - View active JTC channels \`[public]\`",
      "\`!vcpanel\` - Voice Control Panel \`[extra owners]\`",
      "**VC Panel Options:**",
      "- Lock / Unlock Channel",
      "- Hide / Unhide Channel",
      "- Change Bitrate & User Limit",
      "- Transfer Ownership",
      "",
      "\`!theatermode on/off\` - Movie Mode (mutes entire VC) \`[extra owners]\`",
      "\`!vclock / !vcunlock\` - Deny connect perms \`[extra owners]\`",
      "\`!mute / !unmute / !deafen / !undeafen\` - VC state control \`[extra owners]\`",
      "\`!muteall / !unmuteall / !deafenall / !undeafenall\` - Mass state control \`[extra owners]\`",
      "\`!vcstatus on/off\` - Toggle live VC status text \`[extra owners]\`",
      "\`!moveprotect / !vcprotect add|remove\` - Prevent admins from moving/muting protected users \`[server owner]\`",
      "\`!massmove dest / !massdc\` - Move/disconnect everyone \`[extra owners]\`",
      "\`!botvoice\` - Force bot to join/stay in VC \`[admin]\`",
      "\`!vcdrag / !vcdragstop\` - Drag users to your VC \`[extra owners]\`",
      "\`!jtcsetup / !secondaryjtc / !jtcdisable\` - Advanced JTC \`[extra owners]\`",
      "\`!vcdraglist\` - View all currently active VC drag sessions \`[extra owners]\`"
    ] },
    { id: 'music', category: 'VOICE & MEDIA', shortLabel: 'Music', label: 'Music Player', emoji: 'music', commands: [
      "\`/setupmusic [image]\` - Create Compact Music Player channel \`[extra owners]\`",
      "**Music Player Features:**",
      "- Interactive UI Buttons (Play, Pause, Skip)",
      "- Live Lyrics Parsing",
      "- Queue Management",
      "",
      "\`/play query\` - Play a song via URL or search \`[public]\`",
      "\`!skip / !stop / !queue / !pause / !resume\` - Queue management \`[public]\`"
    ] },
    { id: 'tts', category: 'VOICE & MEDIA', shortLabel: 'TTS', label: 'Text-to-Speech', emoji: 'tts', commands: [
      "\`!tts <message>\` - Speak text in VC \`[public]\`",
      "-# Play a text-to-speech message in your current voice channel.",
      "",
      "\`!tts config\` - Change TTS voice and speed \`[public]\`",
      "**TTS Panel Options:**",
      "- Voice Model (Male / Female / Languages)",
      "- Speech Speed Settings",
      "- Voice Effect Adjustments"
    ] },
    { id: 'messaging', category: 'VOICE & MEDIA', shortLabel: 'Messaging', label: 'Announcements', emoji: 'messaging', commands: [
      "\`!say #channel msg\` - Anonymous bot message \`[extra owners]\`",
      "\`!announce #channel title|msg\` - Styled announcement embed \`[extra owners]\`",
      "\`!modmode on/off\` - Restrict channels to moderators \`[extra owners]\`",
      "\`!sticky set / footer / remove\` - Manage sticky messages \`[extra owners]\`",
      "-# Ensures a message always stays at the bottom of a channel by auto-reposting."
    ] },
    
    { id: 'utilities', category: 'UTILITIES & INTEGRATIONS', shortLabel: 'Utility', label: 'General Utilities', emoji: 'utility', commands: [
      "\`!afk [reason]\` - Set AFK status \`[public]\`",
      "\`/bump\` - Set bump reminder \`[public]\`",
      "\`!avatar / !banner [@user]\` - View avatars \`[public]\`",
      "\`!status\` - Security health overview \`[public]\`",
      "\`!bjoins / !bleaves / !bsummary\` - View bot growth stats \`[public]\`",
      "\`!bcmds\` - View most used commands \`[public]\`",
      "\`!bservers\` - View all servers the bot is in \`[public]\`",
      "\`!setmedia #channel\` / \`!unsetmedia\` - Bind auto-media extractor \`[extra owners]\`",
      "-# Automatically downloads and extracts MP4/MP3 media from TikTok, YouTube, Instagram, and Reddit links.",
      "",
      "\`!mp3 link\` - Extract audio from links \`[public]\`",
      "\`!rate [url]\` - Post edit to be rated \`[public]\`",
      "\`!rateleaderboard\` - Top rated edits \`[public]\`",
      "\`!ping / !time\` - Latency and IST \`[public]\`",
      "\`!setup\` - Quick-bind logs, qr VC, qr role \`[extra owners]\`",
      "\`!dev\` - View Developer details \`[public]\`",
      "\`!calc / !calculator\` - Interactive calculator \`[public]\`",
      "\`!upload \\\"name.exe\\\"\` - Upload executable file safely \`[public]\`",
      "\`!quote <msg_id>\` - Canvas quote \`[public]\`",
      "\`!quotemaker\` - Quote generator \`[public]\`",
      "\`!quote setchannel\` - Auto-quote channel \`[admin]\`",
      "\`!qrcode text|url\` - Generate a QR code \`[public]\`",
      "\`/app\` - Application system \`[public]\`",
      "\`!learn\` - Teach bot a new command \`[admin]\`",
      "\`!botstats\` - Advanced bot info \`[public]\`",
      "\`!ytstats\` - YouTube Stats VC \`[admin]\`",
      "\`!backup create\` - Create a full server backup (channels, roles, settings) \`[extra owners]\`",
      "**Backup System Options:**",
      "- Backup Channels & Categories",
      "- Backup Roles & Permissions",
      "- Backup Server Settings",
      "",
      "\`!backup load <id>\` - Restore a server backup instantly \`[extra owners]\`",
      "\`!backup list\` - List all server backups \`[extra owners]\`",
      "\`!backup delete <id>\` - Delete a backup \`[extra owners]\`",
      "\`!steal <emoji>\` - Steal one or more custom emojis into this server \`[extra owners]\`",
      "\`!stealemoji\` - Steal emojis from this server and copy them to another \`[bot owner]\`"
    ] },
    { id: 'customcmds', category: 'UTILITIES & INTEGRATIONS', shortLabel: 'Custom Cmds', label: 'Custom Commands', emoji: 'customcmds', commands: [
      "\`!ccmd add <name> <cmd>\` - Create custom server command \`[admin]\`",
      "\`!ccmd list\` - View custom commands \`[public]\`",
      "\`!ccmd grant @user\` - Grant access \`[admin]\`",
      "\`!ccmd revoke @user\` - Revoke access \`[admin]\`",
      "\`!ccmd access\` - View granted list \`[public]\`"
    ] },
    { id: 'tickets', category: 'UTILITIES & INTEGRATIONS', shortLabel: 'Tickets', label: 'Support Tickets', emoji: 'tickets', commands: [
      "\`!ticket\` - Launch Ticket Panel Builder \`[extra owners]\`",
      "\`!close\` - Close active ticket thread \`[public]\`",
      "\`!ticketpanel\` - Launch interactive ticket panel manager \`[extra owners]\`",
      "\`!ticket\` - Manage the ticket system \`[public]\`",
      "**Ticket System Setup Guide**",
      "\`/ticket setup\` - Instantly deploy the configured ticket panel to your current channel \`[extra owners]\`",
      "**Panel Builder Options:**",
      "- Add Dropdown Options (e.g. Support, Billing)",
      "- Configure Welcome Messages per option",
      "- Restrict Ticket Closing to specific Roles",
      "- Add Panel Banners & Thumbnails",
      "- Customize Panel Titles & Embeds"
    ] },
    { id: 'newsfeed', category: 'UTILITIES & INTEGRATIONS', shortLabel: 'News', label: 'News Feed', emoji: 'newsfeed', commands: [
      "\`!news setup #channel\` - Setup automated news feeds \`[extra owners]\`",
      "\`!news add <source>\` - Subscribe to feeds \`[extra owners]\`",
      "**Supported News Sources:**",
      "- RSS Feeds",
      "- Global Announcements",
      "- Community Updates"
    ] }
  ];`;

const newJs = js.substring(0, startIdx) + newHelpModules + js.substring(endIdx);
fs.writeFileSync("src/commands/utility.js", newJs);
console.log("Safely updated helpModules with immense detail!");
