import { createCanvas, loadImage } from 'canvas';

// Helper to strip standard emojis so they don't render as tofu boxes in node-canvas
function stripEmojis(str) {
  return str.replace(/[\u{1F600}-\u{1F64F}]/gu, '')
            .replace(/[\u{1F300}-\u{1F5FF}]/gu, '')
            .replace(/[\u{1F680}-\u{1F6FF}]/gu, '')
            .replace(/[\u{1F700}-\u{1F77F}]/gu, '')
            .replace(/[\u{1F780}-\u{1F7FF}]/gu, '')
            .replace(/[\u{1F800}-\u{1F8FF}]/gu, '')
            .replace(/[\u{1F900}-\u{1F9FF}]/gu, '')
            .replace(/[\u{1FA00}-\u{1FA6F}]/gu, '')
            .replace(/[\u{1FA70}-\u{1FAFF}]/gu, '')
            .replace(/[\u{2600}-\u{26FF}]/gu, '')
            .replace(/[\u{2700}-\u{27BF}]/gu, '')
            .replace(/<a?:[a-zA-Z0-9_]+:\d+>/g, '') // Also strip discord custom emojis just in case
            .trim();
}

function calculateLines(ctx, text, maxWidth) {
  const paragraphs = text.split('\n');
  const allLines = [];
  
  for (const paragraph of paragraphs) {
    if (!paragraph.trim()) {
      allLines.push('');
      continue;
    }
    const words = paragraph.split(' ');
    let currentLine = '';
    
    for (let n = 0; n < words.length; n++) {
      const testLine = currentLine + words[n] + ' ';
      const metrics = ctx.measureText(testLine);
      if (metrics.width > maxWidth && n > 0) {
        allLines.push(currentLine.trim());
        currentLine = words[n] + ' ';
      } else {
        currentLine = testLine;
      }
    }
    allLines.push(currentLine.trim());
  }
  return allLines;
}

export async function generateQuoteBuffer(username, avatarUrl, text, timestampStr, theme = 'dark', roleColor = '#FFFFFF', realUsername = '') {
  const width = 1200;
  const height = 630;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  
  const cleanUsername = stripEmojis(username);
  const cleanText = stripEmojis(`"${text}"`);
  const cleanRealUsername = realUsername ? stripEmojis(realUsername) : '';
  
  // 1. Draw the user's avatar as the background
  try {
    const bgImage = await loadImage(avatarUrl.replace('.webp', '.png').replace('.gif', '.png') + '?size=1024');
    const scale = Math.max(width / bgImage.width, height / bgImage.height);
    const drawWidth = bgImage.width * scale;
    const drawHeight = bgImage.height * scale;
    const drawX = (width - drawWidth) / 2;
    const drawY = (height - drawHeight) / 2;
    
    ctx.drawImage(bgImage, drawX, drawY, drawWidth, drawHeight);
    
    ctx.fillStyle = 'rgba(0, 0, 0, 0.75)'; // Heavy black tint
    ctx.fillRect(0, 0, width, height);
  } catch (err) {
    ctx.fillStyle = '#111111';
    ctx.fillRect(0, 0, width, height);
  }
  
  // 2. Draw the Quote Text
  const maxTextWidth = 700;
  const textStartX = 400; // Push text to the right side
  
  ctx.fillStyle = '#FFFFFF';
  ctx.font = 'italic 48px sans-serif';
  ctx.textAlign = 'center';
  
  const lines = calculateLines(ctx, cleanText, maxTextWidth);
  const lineHeight = 60;
  const totalTextHeight = lines.length * lineHeight;
  
  const startY = (height - totalTextHeight) / 2 - 40; 
  
  // Draw the lines
  for (let i = 0; i < lines.length; i++) {
    if (lines[i]) {
      ctx.fillText(lines[i], textStartX + (maxTextWidth/2), startY + (i * lineHeight));
    }
  }
  
  const textBottomY = startY + (lines.length * lineHeight);
  
  // 3. Draw the Author
  ctx.font = 'bold 32px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText(`- ${cleanUsername}`, textStartX + (maxTextWidth/2), textBottomY + 50);
  
  if (cleanRealUsername) {
    ctx.font = '24px sans-serif';
    ctx.fillStyle = '#AAAAAA';
    ctx.fillText(`@${cleanRealUsername}`, textStartX + (maxTextWidth/2), textBottomY + 90);
  }
  
  // 4. Draw the Watermark
  ctx.font = '20px sans-serif';
  ctx.fillStyle = '#777777';
  ctx.textAlign = 'right';
  ctx.fillText('Generated by Athena', width - 20, height - 20);
  
  return canvas.toBuffer('image/png');
}
