import { createCanvas, loadImage } from 'canvas';

function wrapText(ctx, text, x, y, maxWidth, lineHeight) {
  const words = text.split(' ');
  let line = '';
  
  // Calculate total height first to center it vertically
  let lines = [];
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + ' ';
    const metrics = ctx.measureText(testLine);
    if (metrics.width > maxWidth && n > 0) {
      lines.push(line);
      line = words[n] + ' ';
    } else {
      line = testLine;
    }
  }
  lines.push(line);
  
  // Draw the lines
  for (let i = 0; i < lines.length; i++) {
    ctx.fillText(lines[i].trim(), x, y + (i * lineHeight));
  }
  return lines.length * lineHeight;
}

export async function generateQuoteBuffer(username, avatarUrl, text, timestampStr, theme = 'dark', roleColor = '#FFFFFF', realUsername = '') {
  const width = 1200;
  const height = 630;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  
  // 1. Draw the user's avatar as the background
  try {
    const bgImage = await loadImage(avatarUrl.replace('.webp', '.png').replace('.gif', '.png') + '?size=1024');
    
    // Calculate aspect ratio to cover the entire canvas
    const scale = Math.max(width / bgImage.width, height / bgImage.height);
    const drawWidth = bgImage.width * scale;
    const drawHeight = bgImage.height * scale;
    const drawX = (width - drawWidth) / 2;
    const drawY = (height - drawHeight) / 2;
    
    // Draw background
    ctx.drawImage(bgImage, drawX, drawY, drawWidth, drawHeight);
    
    // Darken and grayscale overlay to make it look aesthetic
    ctx.fillStyle = 'rgba(0, 0, 0, 0.75)'; // Heavy black tint
    ctx.fillRect(0, 0, width, height);
    
    // Optional: If you want true grayscale, you can manipulate pixels, 
    // but a heavy black semi-transparent overlay usually gives the exact same aesthetic vibe.
  } catch (err) {
    // Fallback black background if avatar fails
    ctx.fillStyle = '#111111';
    ctx.fillRect(0, 0, width, height);
  }
  
  // 2. Draw the Quote Text
  const maxTextWidth = 700;
  const textStartX = 400; // Push text to the right side
  
  ctx.fillStyle = '#FFFFFF';
  ctx.font = 'italic 48px sans-serif';
  ctx.textAlign = 'center';
  
  // Measure text height to center it vertically
  // Rough estimate of height
  const words = `"${text}"`.split(' ');
  let testLine = '';
  let lineCount = 1;
  for (let n = 0; n < words.length; n++) {
    const test = testLine + words[n] + ' ';
    if (ctx.measureText(test).width > maxTextWidth && n > 0) {
      lineCount++;
      testLine = words[n] + ' ';
    } else {
      testLine = test;
    }
  }
  
  const lineHeight = 60;
  const totalTextHeight = lineCount * lineHeight;
  // Center vertically based on text height + author block
  const startY = (height - totalTextHeight) / 2 - 40; 
  
  const textBottomY = startY + wrapText(ctx, `"${text}"`, textStartX + (maxTextWidth/2), startY, maxTextWidth, lineHeight);
  
  // 3. Draw the Author
  ctx.font = 'bold 32px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText(`- ${username}`, textStartX + (maxTextWidth/2), textBottomY + 50);
  
  if (realUsername) {
    ctx.font = '24px sans-serif';
    ctx.fillStyle = '#AAAAAA';
    ctx.fillText(`@${realUsername}`, textStartX + (maxTextWidth/2), textBottomY + 90);
  }
  
  // 4. Draw the Watermark
  ctx.font = '20px sans-serif';
  ctx.fillStyle = '#777777';
  ctx.textAlign = 'right';
  ctx.fillText('Generated by Athena', width - 20, height - 20);
  
  return canvas.toBuffer('image/png');
}
